export { default as Welcome } from './welcome'
export { default as Register } from './register'
export { default as Login } from './login'
export { default as ForgotPassword } from './forgot_password'
export { default as Consult } from './consult'
export { default as FloodingList } from './flooding_list'
export { default as Home } from './home'
export { default as Faq } from './faq'
